language: c

sudo: required

os:
  - linux
  - osx

compiler:
  - clang

  before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - cd ..

script:
  - cmake --build build
  - build/test__all -s
